### ISSUE TITLE
Website is not accessible

### ISSUE THREAD

**Issue by medabalimi** [xcp-ng/xcp-ng-org#6]
The Website does not seem to be accessible. 
![Screenshot_20200503_123625](https://user-images.githubusercontent.com/13141601/80908114-ccb11b80-8d3a-11ea-8e1f-be6d415909bd.png)

**Comment by olivierlambert** [comment]
Hi,

Fixed after a reboot. This outage started around 3:18AM UTC+2 on various VMs with had at various places. We are investigating to find the root cause.

**Comment by olivierlambert** [comment]
Root cause was identified. Read more here: [root@pc-728 raw]# cd ../vhd/
[root@pc-728 vhd]# dd bs=4096 count=2097152 if=/dev/zero of=test2 conv=fdatasync
2097152+0 enregistrements lus
2097152+0 enregistrements écrits
8589934592 octets (8,6 GB, 8,0 GiB) copiés, 50,0682 s, 172 MB/s
[root@pc-728 vhd]# dd bs=4096 count=2097152 if=/dev/zero of=test2 conv=fdatasync
2097152+0 enregistrements lus
2097152+0 enregistrements écrits
8589934592 octets (8,6 GB, 8,0 GiB) copiés, 45,1092 s, 190 MB/s
[root@pc-728 vhd]# dd bs=4096 count=2097152 if=/dev/zero of=test2 conv=fdatasync
2097152+0 enregistrements lus
2097152+0 enregistrements écrits
8589934592 octets (8,6 GB, 8,0 GiB) copiés, 23,9574 s, 359 MB/s
[root@pc-728 vhd]# dd bs=4096 count=2097152 if=/dev/zero of=test2 conv=fdatasync
2097152+0 enregistrements lus
2097152+0 enregistrements écrits
8589934592 octets (8,6 GB, 8,0 GiB) copiés, 23,931 s, 359 MB/s
